# Generated by Django 5.1 on 2024-08-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='season',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
